### ISSUE TITLE
Welcome on Github!

### ISSUE THREAD

**Issue by nigrosimone** [Auctollo/google-sitemap-generator#1]
Hi w3edge's folks,
maybe isn't the right place, i have just noticed this new project.

Just a little (off-topic) question: you have any plan for put on GitHub your main project W3 Total Cache?

I'm already one of developers of the community version [W3 Total Cache Fixed](https://github.com/szepeviktor/w3-total-cache-fixed).

**Comment by maxicus** [comment]
We will put it on github too in a future too. Aware about your work, thank you for participating.
