### ISSUE TITLE
Exclude the RSS-Feeds-Sits from sitemap.....

### ISSUE THREAD

**Issue by Wegisto** [Auctollo/google-sitemap-generator#110]
Hallo together,

is it possible to exclude the .../feed/ from the sitemap-Files in an easy way? I'm just new and didn't find an option in the settings....

Google marked a lot of feed sites as not listed....

Thanks in advance & Best Regards

Gerhard

**Comment by Wegisto** [comment]
Hallo,
in the google search console are the feed-sites listed:

 pages ->page indexing -> Crawled - currently not indexed
 
 Bye
 
 Vegisto

**Comment by ftownes** [comment]
Ok, these two issues are not related. Please use the wordpress.org forums for support topics in the future.
