### ISSUE TITLE
Question about the site map

### ISSUE THREAD

**Issue by seminiva** [Auctollo/google-sitemap-generator#113]
Hello everyone, I have a blog https://pyatilistnik.org/, the question is, I updated the plugin version, and now I have some kind of phantom sitemaps.

main site map https://pyatilistnik.org/sitemap.xml
it has https://pyatilistnik.org/sitemap-pt-post-p1-2023-10.xml, and it turns out that the old names https://pyatilistnik.org/sitemap-pt-page-2018-09.xml and
https://pyatilistnik.org/sitemap-pt-page-2018-05.xml and they are empty, how to find these submaps and delete them?

**Comment by ftownes** [comment]
Hello, unfortunately, these sitemaps are programmatically generated and cannot be manually deleted. The latest release should resolve this issue. In the future, please use the wordpress.org forums for support.
