### ISSUE TITLE
/sitemap.xml

### ISSUE THREAD

**Issue by allee0000** [Auctollo/google-sitemap-generator#184]

**Comment by allee0000** [comment]
Discovery
Not checked in live tests
Crawl
Time
Feb 20, 2024, 2:07:47 AM
Crawled as
Google Inspection Tool smartphone
Crawl allowed?
error
No: blocked by robots.txt
Page fetch
error
Failed: Blocked by robots.txt
Indexing allowed?
N/A
Indexing
User-declared canonical
N/A
Google-selected canonical
[](https://search.google.com/#)
Only determined after indexing 
    My website sitemap could not fetch on Google and show something given above, 
My site URL in now indexted and I want to fix this error on robot.txt file

**Comment by ftownes** [comment]
This is a support issue, please use the [forums](https://wordpress.org/support/plugin/google-sitemap-generator/)
