### ISSUE TITLE
One or more plugins conflict with proper indexation of your website. Use the deactivate button below to disable the extra sitemaps:

### ISSUE THREAD

**Issue by andy-1977** [Auctollo/google-sitemap-generator#187]
After updating to the latest version of this plugin, the below error message appears in the top left of the Wordpress dashboard.

**One or more plugins conflict with proper indexation of your website. Use the deactivate button below to disable the extra sitemaps**

This is a false positive, as the only sitemap being generated is via this plugin, and the warning message only appeared after updating to the latest version of this plugin.

PHP Version 8.2

XML Sitemap Generator For Google: V4.1.19

If this could be investigated, that would be brilliant!

**Comment by ftownes** [comment]
Please use the forum for [support topics](https://wordpress.org/support/plugin/google-sitemap-generator/).

**Comment by andy-1977** [comment]
Was posted in the forum 2 weeks ago, with no response (details below):

https://wordpress.org/support/topic/one-or-more-plugins-conflict-with-proper-indexation-of-your-website/

Not sure why you've closed this, as it's clearly a software bug, which needs addressing!
