### ISSUE TITLE
Not submitting sitemap

### ISSUE THREAD

**Issue by Jojo1370** [Auctollo/google-sitemap-generator#90]
sitemapThere is still a sitemap.xml or sitemap.xml.gz file in your site directory. Please delete them as no static files are used anymore or <a href='%s'>try to delete them automatically</a>.
The URL to your sitemap index file is: https://www.joelibrandi.com/sitemap.xml.
Search engines haven't been notified yet. Write a post to let them know about your sitemap.
Notify Search Engines about [your sitemap ](https://www.joelibrandi.com/wp-admin/options-general.php?page=google-sitemap-generator%2Fsitemap.php&sm_ping_main=true&_wpnonce=02d6c1b1d9)or [your main sitemap and all sub-sitemaps](https://www.joelibrandi.com/wp-admin/options-general.php?page=google-sitemap-generator%2Fsitemap.php&sm_ping_main=true&_wpnonce=02d6c1b1d9) now.
If you encounter any problems with your sitemap you can use the [debug function](https://www.joelibrandi.com/wp-admin/options-general.php?page=google-sitemap-generator%2Fsitemap.php&sm_rebuild=true&sm_do_debug=true&_wpnonce=02d6c1b1d9) to get more information.

**Comment by saurabhd** [comment]
@Jojo1370 ,

Kindly mention your query in the forum https://wordpress.org/support/plugin/google-sitemap-generator/.
