### ISSUE TITLE
Link redirection in Google search display ( help ) 

### ISSUE THREAD

**Issue by classicfaz** [Auctollo/google-sitemap-generator#96]
Hello . I have a problem. My site opens normally. It is not a problem to type the website address manually. But in Google search, when I click on the site, it redirects to an unknown address. please guide me .

**Comment by classicfaz** [comment]
my website :  ` https://rasanehcenter.com/ `
It opens without any problems

---------------------------
But in Google results
Search on Google: 
` رسانه سنتر `

And click on the site.
The site will be moved to another address and that site will be displayed!



[The link of the site to which it is transferred](https://1419.sapecuhow.live/qldndyhv/?utm_campaign=INccHxHRWrew3TQsLBbfNnbGFYUZobMqxXT9Zrw5FhI1%26t=main9%26f=1%26sid=t3~ohdcpocufhfo45y4huoyfcnn%26fp=zS75JSUWlR97PE9WS5%252F1pTxneOpb6Tej8AOgZu8IM87NTw1uC4vgTAtNOs%252FYB1StZm6gdUmmMABCit7tjg3OhLl4Ihgc0sQQsqoLgTYcUKv9h0MVlZF8Yd6XxKkDBRiOkaa77VFGN%252BaXsn%252B4oZy2V8r%252BF5Tg3OaglZWTUVg4FJc6il0XSoOKVeNwHpSzYvqAM446POm4QUYorW0M66%252BjZQrnQsMrZtEoEDFBUSY%252Fa7n7hLTpUePM6o1rZ88Sa5mUQoNkqO7zShBtEV4shh0SfCuuha6%252Frl1J59GJpxghz%252FgWZGXzFBHAgflnqzYSasVQwrTXga9EOkxTgM%252Bdoo6SVHp3UAfkcaVs09PNKm6A3dBYusxnLc3tccMO%252BIBrjIueONYZb2eYAN8DOILbGTbjGix6zbczed15cW5g8Y%252FGsES4B0OnRWW%252ByDsHQimI7Hn1VY3vsVm6Q6Tuvfqzbs7EZn%252FM5KkfrouEVdywm%252F2nuJ0MV6VmWSS54GDtJWb7734o7LkK9ni456E51ezdz4yC5Ry9GjeosWJtm2%252B9m9uN8CGeEqcVUDTzhcAB7FnnZSbYYLwdyFYk%252FsKhrt6vGpEfTJ98LUiPmcHL04QUHpCxqBx3o8KCc1fm0PPB47sO%252BlSoxp8KGKrl5SGmvRHTuK9Oto4lH89CTsvAophIZFbJe5R8O6zTz7FK8lM%252Fl1uP1GgsHjwAkQlb%252BRRPTww4qXHBIxDXIYdSz7AeOZ0NsEsTusDkMwB5teXKIp1JDp%252BM0Fc8%252BQ8YqaMQQBZH8aUbbAABl9vJKmCJnvkIj%252Fj%252BeDnqZE1RbJOmGo5vVcIoctE5%252FFwRO2ae%252BOBazfrmatLYW1ldI7o8Mm%252BDGB0Lpq5RlY5f2dre8UF64ao0z%252FeQtHGDGMC46QEXNtd%252FTlUYTuSv2YR3HtIyxdfPp2qFOfFIVok3aNgOz05BTlcw4MlfTcNOvhyEZLO50qHRTpfRnXKWclQz64Jmi2%252B0oOOubvJbjbEAR4ic7plCzY8T0EfxocmApsKvJdcgtKxpN6ZtJ7CtVE3QrULvu5WwM28vEu0pyBOh9ie%252BRRAtxrzZF4K7EJhEyFbIU0PAfdubYeOOpoV97KWSMdd1MwgXiMZ1xhl%252F1xub2Lt8VA25U631UAgcDNXCSjUxZ76ydV%252FmjNBza%252BymI34FiJJO6CTFpQtlc97eR0SmmiKHhM2kySdmmSRrM9EZB4LFTCLfJru%252BnBZmae%252FS5RKFsf7buQ1agZiCYDYGJy8eFCO2Uoj4go4E%252FFuTRzFXTvQCFEEXhomshKNHjl%252F15qVAZpnDg4fVGuAOMxXhLAI8BpTr%252BBocVOvpI7y4DCVnKlEH1MORzgk%252F%252FMen6%252Fm1looibmsqxgYf%252FCvGogAizkYVTp5G%252BReriIPTMxmYmjRpQ25LranUT45WKGdhW6fiS1x2GSGOId5Aq5Vw1QvcQnfa0GqpJlQzRyGWTyRDpd7lngQ7ZMbQpy%252BvTz4ctQ2z9dNVSfMbw9PWG4rLy1sTEm6c2fDsY6hgsf%252BdMAAYURItG73CMzIghBSQ0jNYD%252FNKkwe%252FMI0tGw661YVVCIkS7fPGgrt3pVJWv3CVeB1iqRKFdi2NxIGqncFxqQI5GKTdsa8eRAl7mUFXK2aoCBZponPkOlkMtsezc9DmZ%252B7KyRpPKhJF1THfgkvmq%252Bko7niAynLUiol%252Bk5WLIde8CysRpRVBerBYs0WeQL7MxDLfIFjUtYt6cSKgScYYYRiVY23hZSkhzhzT0c5%252FBtKbBeyaB1OfDn6YKFvpYLWqZp2KxllPu17%252FJS2Qa4W6zdRQ%252BtxGcT1bBCu5lkZWts6vwQAyVaacoZgF4OmzZvqHkEKcdWondhP0Y48u40%252FsXT10j0vVkFbQ5pbRskCvbmz%252FiMsl5KTQ%252F2CLWzlInPfU4HvwO5NRjRttn1TwGmILO3UD1uQ%252BJr6aZu9JoY%252BdDeigEow4ssI2iD9g1%252F1DyAwCGgheqPcfKBk8pawt935J3EI98Y8eKMObdgQy56KGG1nRfpwsPwgtReu5xO9prztaAS%252BSmjWTLlfPd%252FpzF1cSBaT%252B083ceCzgQQdzI19A1jejKDogKzpbvpw%253D)

please guide me

**Comment by ftownes** [comment]
Sorry, this issue isn't directly related to the plugin.
